import {
  Activity,
  BarChart2,
  BookOpen,
  Box,
  Calculator,
  Code2,
  Dices,
  FileText,
  Flag,
  LineChart,
  ListChecks,
  MessageSquare,
  Sigma,
  SlidersHorizontal,
  Table2,
  TrendingUp,
} from 'lucide-react'

export const PRIMITIVE_CATEGORIES = [
  'Data',
  'Analysis',
  'Math',
  'Compute',
  'Visual',
  'Audit',
  'Write',
]

export const PRIMITIVES = [
  {
    category: 'Data',
    color: 'var(--accent-blue)',
    icon: Table2,
    id: 'table',
    name: 'Table',
  },
  {
    category: 'Data',
    color: 'var(--accent-blue)',
    icon: BarChart2,
    id: 'chart',
    name: 'Chart',
  },
  {
    category: 'Data',
    color: 'var(--accent-blue)',
    icon: Activity,
    id: 'stats-block',
    name: 'Statistics',
  },
  {
    category: 'Analysis',
    color: 'var(--accent-green)',
    icon: TrendingUp,
    id: 'regression',
    name: 'Regression',
  },
  {
    category: 'Analysis',
    color: 'var(--accent-green)',
    icon: LineChart,
    id: 'time-series',
    name: 'Time Series',
  },
  {
    category: 'Analysis',
    color: 'var(--accent-green)',
    icon: Dices,
    id: 'monte-carlo',
    name: 'Monte Carlo',
  },
  {
    category: 'Math',
    color: 'var(--accent-purple)',
    icon: Sigma,
    id: 'equation',
    name: 'Equation',
  },
  {
    category: 'Math',
    color: 'var(--accent-purple)',
    icon: Calculator,
    id: 'formula-block',
    name: 'Formula',
  },
  {
    category: 'Math',
    color: 'var(--accent-purple)',
    icon: SlidersHorizontal,
    id: 'parameter-node',
    name: 'Parameters',
  },
  {
    category: 'Compute',
    color: 'var(--accent-orange)',
    icon: Code2,
    id: 'code-editor',
    name: 'Code',
  },
  {
    category: 'Visual',
    color: 'var(--accent-red)',
    icon: Box,
    id: '3d-object',
    name: '3D Viewer',
  },
  {
    category: 'Visual',
    color: 'var(--accent-red)',
    icon: MessageSquare,
    id: 'annotation',
    name: 'Annotation',
  },
  {
    category: 'Audit',
    color: 'var(--accent-orange)',
    icon: Flag,
    id: 'assumption-flag',
    name: 'Assumptions',
  },
  {
    category: 'Audit',
    color: 'var(--accent-orange)',
    icon: ListChecks,
    id: 'progress-step',
    name: 'Progress',
  },
  {
    category: 'Write',
    color: 'var(--text-secondary)',
    icon: FileText,
    id: 'prose-block',
    name: 'Prose',
  },
  {
    category: 'Write',
    color: 'var(--text-secondary)',
    icon: BookOpen,
    id: 'notebook',
    name: 'Notebook',
  },
]

export function getPrimitiveDefinition(primitiveType) {
  return PRIMITIVES.find((primitive) => primitive.id === primitiveType) ?? null
}
