import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { getThemeToken } from '../styles/themeTokens'

const paperSizes = {
  A3: { height: 297, width: 420 },
  A4: { height: 210, width: 297 },
  Letter: { height: 216, width: 279 },
}

function dispatchExportToast(message, type = 'info') {
  window.dispatchEvent(
    new CustomEvent('nexus-toast', {
      detail: { message, type },
    }),
  )
}

function getCanvasSize(paperSize, orientation) {
  const size = paperSizes[paperSize] ?? paperSizes.A4

  if (orientation === 'portrait') {
    return {
      height: Math.max(size.height, size.width),
      width: Math.min(size.height, size.width),
    }
  }

  return {
    height: Math.min(size.height, size.width),
    width: Math.max(size.height, size.width),
  }
}

function sanitizeFilename(value) {
  return String(value || 'NEXUS_Analysis')
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '_')
}

// NEXUS Export Engine
// Captures the canvas and all visible blocks as a PDF report
// AGENT: can trigger export via nex export pdf command
export async function exportCanvasToPDF(projectName = 'NEXUS Analysis', options = {}) {
  const canvas = document.getElementById('nexus-canvas')
  if (!canvas) throw new Error('Canvas not found')

  dispatchExportToast('Preparing export...')

  try {
    const scale = Number(options.resolution) || 2
    const includeCoverPage = options.includeCoverPage !== false
    const paperSize = options.paperSize || 'A4'
    const canvasImage = await html2canvas(canvas, {
      allowTaint: true,
      backgroundColor: getThemeToken('--bg-base', '#0b0f14'),
      logging: false,
      scale,
      useCORS: true,
    })
    const imgData = canvasImage.toDataURL('image/png')
    const imgWidth = canvasImage.width
    const imgHeight = canvasImage.height
    const { height: pdfHeight, width: pdfWidth } = getCanvasSize(
      paperSize,
      'landscape',
    )
    const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight)
    const scaledWidth = imgWidth * ratio
    const scaledHeight = imgHeight * ratio
    const pdf = new jsPDF({
      format: paperSize.toLowerCase(),
      orientation: 'landscape',
      unit: 'mm',
    })

    if (includeCoverPage) {
      pdf.setFillColor(11, 15, 20)
      pdf.rect(0, 0, pdfWidth, pdfHeight, 'F')
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(32)
      pdf.setFont('helvetica', 'bold')
      pdf.text(projectName, pdfWidth / 2, pdfHeight / 2 - 20, {
        align: 'center',
      })
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(150, 150, 180)
      pdf.text('Generated by NEXUS IDE', pdfWidth / 2, pdfHeight / 2, {
        align: 'center',
      })
      pdf.text(
        new Date().toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'long',
          year: 'numeric',
        }),
        pdfWidth / 2,
        pdfHeight / 2 + 10,
        { align: 'center' },
      )
      pdf.addPage()
    }

    pdf.setFillColor(11, 15, 20)
    pdf.rect(0, 0, pdfWidth, pdfHeight, 'F')
    pdf.addImage(
      imgData,
      'PNG',
      (pdfWidth - scaledWidth) / 2,
      (pdfHeight - scaledHeight) / 2,
      scaledWidth,
      scaledHeight,
    )
    pdf.setFontSize(8)
    pdf.setTextColor(100, 100, 120)
    pdf.text('NEXUS IDE — nexus-ide.app', pdfWidth / 2, pdfHeight - 5, {
      align: 'center',
    })

    const filename = `${sanitizeFilename(projectName)}_${new Date()
      .toISOString()
      .split('T')[0]}.pdf`
    pdf.save(filename)
    dispatchExportToast(`Exported: ${filename}`, 'success')
  } catch (error) {
    dispatchExportToast('Export failed. Try again.', 'error')
    console.error('Export error:', error)
  }
}

export async function exportNotebookToPDF(notebookEl, title = 'Notebook', options = {}) {
  if (!notebookEl) return

  dispatchExportToast('Exporting notebook...')

  try {
    const scale = Number(options.resolution) || 2
    const paperSize = options.paperSize || 'A4'
    const canvasImage = await html2canvas(notebookEl, {
      backgroundColor: getThemeToken('--bg-float', '#1e2530'),
      logging: false,
      scale,
      useCORS: true,
    })
    const imgWidth = canvasImage.width
    const imgHeight = canvasImage.height
    const { height: pdfHeight, width: pdfWidth } = getCanvasSize(
      paperSize,
      'portrait',
    )
    const margin = 15
    const contentWidth = pdfWidth - margin * 2
    const ratio = contentWidth / imgWidth
    const scaledHeight = imgHeight * ratio
    const pdf = new jsPDF({
      format: paperSize.toLowerCase(),
      orientation: 'portrait',
      unit: 'mm',
    })

    pdf.setFillColor(21, 27, 35)
    pdf.rect(0, 0, pdfWidth, pdfHeight, 'F')
    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(18)
    pdf.setFont('helvetica', 'bold')
    pdf.text(title, margin, margin + 5)
    pdf.setFontSize(9)
    pdf.setTextColor(150, 150, 180)
    pdf.text(`NEXUS IDE  •  ${new Date().toLocaleDateString()}`, margin, margin + 12)

    let yPosition = margin + 20
    let remainingHeight = scaledHeight
    let sourceY = 0

    while (remainingHeight > 0) {
      const pageContentHeight = pdfHeight - yPosition - margin
      const sliceHeight = Math.min(remainingHeight, pageContentHeight)
      const sourceSliceHeight = sliceHeight / ratio
      const sliceCanvas = document.createElement('canvas')
      sliceCanvas.width = imgWidth
      sliceCanvas.height = sourceSliceHeight
      const context = sliceCanvas.getContext('2d')
      context.drawImage(canvasImage, 0, -sourceY)
      pdf.addImage(
        sliceCanvas.toDataURL('image/png'),
        'PNG',
        margin,
        yPosition,
        contentWidth,
        sliceHeight,
      )
      remainingHeight -= sliceHeight
      sourceY += sourceSliceHeight

      if (remainingHeight > 0) {
        pdf.addPage()
        pdf.setFillColor(21, 27, 35)
        pdf.rect(0, 0, pdfWidth, pdfHeight, 'F')
        yPosition = margin
      }
    }

    pdf.setFontSize(8)
    pdf.setTextColor(100, 100, 120)
    pdf.text('NEXUS IDE', pdfWidth / 2, pdfHeight - 5, { align: 'center' })

    const filename = `${sanitizeFilename(title)}_notebook_${new Date()
      .toISOString()
      .split('T')[0]}.pdf`
    pdf.save(filename)
    dispatchExportToast(`Notebook exported: ${filename}`, 'success')
  } catch (error) {
    dispatchExportToast('Notebook export failed.', 'error')
    console.error('Notebook export error:', error)
  }
}
